Create Madhavi Bhagat
rchidana/19Feb2021-Test pull request #1
Opened 2021-02-19 11:07 UTC by Bhagat-github

My Test Answers

2021-02-19 11:08 UTC, rchidana requested changes
Sorry, please buy me a coffee!!!

2021-02-19 11:36 UTC, Bhagat-github reviewed
1.d
2.b
3.c
4.c
5.a
6.a,b
7.b
8.c
9. b
10. a
11. c
12. c
13. c
14. a.b
15. b
16. a
17. b
18. b, c
19. b,c
20. c

2021-02-19 11:38 UTC, Bhagat-github commented
complete test answers

2021-02-20 15:36 UTC, rchidana approved these changes

2021-02-20 15:36 UTC, merged